version: 2
jobs:
  build:
    docker:
    - image: circleci/node:7.10
    working_directory: ~/plantuml_react
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn test
    - add_ssh_keys:
        fingerprints:
        - b3:6d:e8:7d:75:f9:ef:c6:43:50:6c:f1:10:47:65:52
    - run: sudo apt-get update && sudo apt-get install rsync
    - run:
        name: Add to known hosts
        command: |
          mkdir -p ~/.ssh && echo "plantuml.apollov.tk,188.242.234.153 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChD0BcUWrLgvLFNiNRQhfNKTz1Un9B7324K8lc2Aod2mysBDWfzOel9hloQ0gjy89QYrvSwBdTHizOy57c+X28UghMT50N36C9GhTRyGMj8y696gURnD1+Gb0cqUwhJx20UoLlwsn0OlbspAz4uDyUGKaV8Gz5jxmYcvexbbFxdqoWRgXbQr8vHmOB5gzdFudsAyfamEt29B4YO602cfcsB/dHKt9QbJZhTZLt7CLuhOWS7N7/U7+jvS6OUSNXmJ+ZNMgx86I+MF0d/bsWAM3pO3JGtDRDew3EpDIUfCEFFR638vc4XQQ7vSdrPaB6cxg8VvxRt47eoPv7MMn9HRLx" > ~/.ssh/known_hosts
    - run: npm run-script build
    - deploy:
        name: Deploy Over SSH
        command: |
          if [ "${CIRCLE_BRANCH}" = "master" ]; then
            rsync -avcze ssh -delete ~/plantuml_react/build/ plantuml_react@plantuml.apollov.tk:/home/plantuml_react/www
          else
            echo "Not master branch, dry run only"
          fi
