version: 2
jobs:
  build:
    docker:
    - image: circleci/node:7.10
    working_directory: ~/plantuml_react
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn test
    - add_ssh_keys:
        fingerprints:
        - b3:6d:e8:7d:75:f9:ef:c6:43:50:6c:f1:10:47:65:52
    - run: sudo apt-get install rsync
    - deploy:
        name: Deploy Over SSH
        command: |
          if [ "${CIRCLE_BRANCH}" = "master" ]; then
            rsync -avcze ssh ~/plantuml_react/build/ plantuml_react@apollov.tk:/home/plantuml_react/www
          else
            echo "Not master branch, dry run only"
          fi
